[2025-06-27T17:17:27.779+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-27T17:17:27.799+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-06-27T17:04:46.124401+00:00 [queued]>
[2025-06-27T17:17:27.804+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform manual__2025-06-27T17:04:46.124401+00:00 [queued]>
[2025-06-27T17:17:27.804+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-27T17:17:27.813+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-06-27 17:04:46.124401+00:00
[2025-06-27T17:17:27.818+0000] {standard_task_runner.py:63} INFO - Started process 176 to run task
[2025-06-27T17:17:27.822+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform', 'manual__2025-06-27T17:04:46.124401+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpk78u6_vh']
[2025-06-27T17:17:27.824+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask transform
[2025-06-27T17:17:27.839+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-27T17:17:27.874+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_pipeline.transform manual__2025-06-27T17:04:46.124401+00:00 [running]> on host 0d75e667484d
[2025-06-27T17:17:27.943+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='karo' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-06-27T17:04:46.124401+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-27T17:04:46.124401+00:00'
[2025-06-27T17:17:27.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-27T17:17:28.015+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-27T17:17:28.016+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 220, in _na_arithmetic_op
    result = func(left, right)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 242, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore[misc]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/computation/expressions.py", line 73, in _evaluate_standard
    return op(a, b)
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 44, in transform
    df.loc[mask, "Total Spent"] = df["Quantity"] * df["Price Per Unit"]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/ops/common.py", line 76, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/arraylike.py", line 202, in __mul__
    return self._arith_method(other, operator.mul)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/series.py", line 5819, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/base.py", line 1381, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 285, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 229, in _na_arithmetic_op
    result = _masked_arith_op(left, right, op)
  File "/home/airflow/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 165, in _masked_arith_op
    result[mask] = op(xrav[mask], yrav[mask])
TypeError: can't multiply sequence by non-int of type 'float'
[2025-06-27T17:17:28.026+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=transform, run_id=manual__2025-06-27T17:04:46.124401+00:00, execution_date=20250627T170446, start_date=20250627T171727, end_date=20250627T171728
[2025-06-27T17:17:28.035+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task transform (can't multiply sequence by non-int of type 'float'; 176)
[2025-06-27T17:17:28.074+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-27T17:17:28.089+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-27T17:17:28.093+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
